/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about the uploaded instance, or list of information for each uploaded instance in the case of ZIP archive
 */
export interface InstancesPost200Response { 
    /**
     * Orthanc identifier of the new instance
     */
    ID?: string;
    /**
     * Orthanc identifier of the parent patient
     */
    ParentPatient?: string;
    /**
     * Orthanc identifier of the parent series
     */
    ParentSeries?: string;
    /**
     * Orthanc identifier of the parent study
     */
    ParentStudy?: string;
    /**
     * Path to the new instance in the REST API
     */
    Path?: string;
    /**
     * Can be `Success`, `AlreadyStored`, `Failure`, or `FilteredOut` (removed by some `NewInstanceFilter`)
     */
    Status?: string;
}

