/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface InstancesIdAnonymizePostRequest { 
    /**
     * Version of the DICOM standard to be used for anonymization. Check out configuration option `DeidentifyLogsDicomVersion` for possible values.
     */
    DicomVersion?: string;
    /**
     * Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world
     */
    Force?: boolean;
    /**
     * List of DICOM tags whose value must not be destroyed by the anonymization. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).
     */
    Keep?: Array<string>;
    /**
     * Keep the labels of all resources level (defaults to `false`)
     */
    KeepLabels?: boolean;
    /**
     * Keep the private tags from the DICOM instances (defaults to `false`)
     */
    KeepPrivateTags?: boolean;
    /**
     * If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.
     */
    KeepSource?: boolean;
    /**
     * The private creator to be used for private tags in `Replace`
     */
    PrivateCreator?: string;
    /**
     * List of additional tags to be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).
     */
    Remove?: Array<string>;
    /**
     * Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).
     */
    Replace?: object;
    /**
     * Transcode the DICOM instances to the provided DICOM transfer syntax: https://orthanc.uclouvain.be/book/faq/transcoding.html
     */
    Transcode?: string;
}

