/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ModalitiesIdPutRequest { 
    /**
     * AET of the remote DICOM modality
     */
    AET?: string;
    /**
     * Whether to accept C-ECHO SCU commands issued by the remote modality
     */
    AllowEcho?: boolean;
    /**
     * Whether to accept C-FIND SCU commands issued by the remote modality
     */
    AllowFind?: boolean;
    /**
     * Whether to accept C-FIND SCU commands for worklists issued by the remote modality
     */
    AllowFindWorklist?: boolean;
    /**
     * Whether to accept C-GET SCU commands issued by the remote modality
     */
    AllowGet?: boolean;
    /**
     * Whether to accept C-MOVE SCU commands issued by the remote modality
     */
    AllowMove?: boolean;
    /**
     * Whether to accept storage commitment requests issued by the remote modality
     */
    AllowStorageCommitment?: boolean;
    /**
     * Whether to accept C-STORE SCU commands issued by the remote modality
     */
    AllowStore?: boolean;
    /**
     * Whether to allow transcoding for operations initiated by this modality. This option applies to Orthanc C-GET SCP and to Orthanc C-STORE SCU. It only has an effect if the global option `EnableTranscoding` is set to `true`.
     */
    AllowTranscoding?: boolean;
    /**
     * Host address of the remote DICOM modality (typically, an IP address)
     */
    Host?: string;
    /**
     * Manufacturer of the remote DICOM modality (check configuration option `DicomModalities` for possible values
     */
    Manufacturer?: string;
    /**
     * TCP port of the remote DICOM modality
     */
    Port?: number;
    /**
     * Whether to use DICOM TLS in the SCU connection initiated by Orthanc (new in Orthanc 1.9.0)
     */
    UseDicomTls?: boolean;
}

