/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface PatientsIdStatisticsGet200Response { 
    /**
     * Number of child instances within this patient
     */
    CountInstances?: number;
    /**
     * Number of child series within this patient
     */
    CountSeries?: number;
    /**
     * Number of child studies within this patient
     */
    CountStudies?: number;
    /**
     * Size on the disk of the DICOM instances associated with the patient, expressed in bytes
     */
    DicomDiskSize?: string;
    /**
     * Size on the disk of the DICOM instances associated with the patient, expressed in megabytes (MB)
     */
    DicomDiskSizeMB?: number;
    /**
     * Size on the disk of the uncompressed DICOM instances associated with the patient, expressed in bytes
     */
    DicomUncompressedSize?: string;
    /**
     * Size on the disk of the uncompressed DICOM instances associated with the patient, expressed in megabytes (MB)
     */
    DicomUncompressedSizeMB?: number;
    /**
     * Size of the patient on the disk in bytes, expressed as a string for 64bit compatibility with JSON
     */
    DiskSize?: string;
    /**
     * Size of the patient on the disk, expressed in megabytes (MB)
     */
    DiskSizeMB?: number;
    /**
     * Size of the patient after decompression in bytes, expressed as a string for 64bit compatibility with JSON
     */
    UncompressedSize?: string;
    /**
     * Size of the patient after decompression, expressed in megabytes (MB). This is different from `DiskSizeMB` iff `StorageCompression` is `true`.
     */
    UncompressedSizeMB?: number;
}

