/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface PeersIdPutRequest { 
    /**
     * SSL certificate for the HTTPS connections
     */
    CertificateFile?: string;
    /**
     * Key file for the SSL certificate for the HTTPS connections
     */
    CertificateKeyFile?: string;
    /**
     * Key password for the SSL certificate for the HTTPS connections
     */
    CertificateKeyPassword?: string;
    /**
     * HTTP headers to be used for the connections to the remote peer
     */
    HttpHeaders?: object;
    /**
     * Password for the credentials
     */
    Password?: string;
    /**
     * URL of the root of the REST API of the remote Orthanc peer, for instance `http://localhost:8042/`
     */
    URL?: string;
    /**
     * Username for the credentials
     */
    Username?: string;
}

