/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface QueriesIdAnswersIndexRetrievePostRequest { 
    /**
     * If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.
     */
    Asynchronous?: boolean;
    /**
     * If set to `true`, report the DICOM tags in full format (tags indexed by their hexadecimal format, associated with their symbolic name and their value)
     */
    Full?: boolean;
    /**
     * If `true`, ignore errors during the individual steps of the job.
     */
    Permissive?: boolean;
    /**
     * In asynchronous mode, the priority of the job. The lower the value, the higher the priority.
     */
    Priority?: number;
    /**
     * If set to `true`, report the DICOM tags in human-readable format (using the symbolic name of the tags)
     */
    Simplify?: boolean;
    /**
     * If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.
     */
    Synchronous?: boolean;
    /**
     * AET of the target modality. By default, the AET of Orthanc is used, as defined in the `DicomAet` configuration option.
     */
    TargetAet?: string;
    /**
     * Timeout for the C-MOVE command, in seconds
     */
    Timeout?: number;
}

