/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface StatisticsGet200Response { 
    /**
     * Number of DICOM instances stored in Orthanc
     */
    CountInstances?: number;
    /**
     * Number of patients stored in Orthanc
     */
    CountPatients?: number;
    /**
     * Number of DICOM series stored in Orthanc
     */
    CountSeries?: number;
    /**
     * Number of DICOM studies stored in Orthanc
     */
    CountStudies?: number;
    /**
     * Size of the storage area (in bytes)
     */
    TotalDiskSize?: string;
    /**
     * Size of the storage area (in megabytes)
     */
    TotalDiskSizeMB?: number;
    /**
     * Total size of all the files once uncompressed (in bytes). This corresponds to `TotalDiskSize` if no compression is enabled, cf. `StorageCompression` configuration option
     */
    TotalUncompressedSize?: string;
    /**
     * Total size of all the files once uncompressed (in megabytes)
     */
    TotalUncompressedSizeMB?: number;
}

