/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface StudiesIdSplitPostRequest { 
    /**
     * If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.
     */
    Asynchronous?: boolean;
    /**
     * The list of instances to be separated from the parent study. These instances must all be children of the same source study, that is specified in the URI.
     */
    Instances?: Array<string>;
    /**
     * Keep the labels of all resources level (defaults to `false`)
     */
    KeepLabels?: boolean;
    /**
     * If set to `true`, instructs Orthanc to keep a copy of the original series/instances in the source study. By default, the original series/instances are deleted from Orthanc.
     */
    KeepSource?: boolean;
    /**
     * If `true`, ignore errors during the individual steps of the job.
     */
    Permissive?: boolean;
    /**
     * In asynchronous mode, the priority of the job. The lower the value, the higher the priority.
     */
    Priority?: number;
    /**
     * List of tags that must be removed in the new study (from the same modules as in the `Replace` option)
     */
    Remove?: Array<string>;
    /**
     * Associative array to change the value of some DICOM tags in the new study. These tags must be part of the \"Patient Module Attributes\" or the \"General Study Module Attributes\", as specified by the DICOM 2011 standard in Tables C.7-1 and C.7-3.
     */
    Replace?: object;
    /**
     * The list of series to be separated from the parent study. These series must all be children of the same source study, that is specified in the URI.
     */
    Series?: Array<string>;
    /**
     * If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.
     */
    Synchronous?: boolean;
}

