/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface SystemGet200Response { 
    /**
     * Version of the REST API
     */
    ApiVersion?: number;
    /**
     * Whether Orthanc handle revisions of metadata and attachments to deal with multiple writers (new in Orthanc 1.9.2)
     */
    CheckRevisions?: boolean;
    /**
     * Information about the installed database index plugin (`null` if no such plugin is installed)
     */
    DatabaseBackendPlugin?: string;
    /**
     * ID of the server in the database (when running multiple Orthanc on the same DB)
     */
    DatabaseServerIdentifier?: string;
    /**
     * Version of the database: https://orthanc.uclouvain.be/book/developers/db-versioning.html
     */
    DatabaseVersion?: number;
    /**
     * The DICOM AET of Orthanc
     */
    DicomAet?: string;
    /**
     * The port to the DICOM server of Orthanc
     */
    DicomPort?: number;
    /**
     * Whether the database back-end supports labels (new in Orthanc 1.12.0)
     */
    HasLabels?: boolean;
    /**
     * The port to the HTTP server of Orthanc
     */
    HttpPort?: number;
    /**
     * Whether instances are transcoded when ingested into Orthanc (`` if no transcoding is performed) (new in Orthanc 1.11.0)
     */
    IngestTranscoding?: string;
    /**
     * Whether the REST API is properly secured (assuming no reverse proxy is in use): https://orthanc.uclouvain.be/book/faq/security.html#securing-the-http-server
     */
    IsHttpServerSecure?: boolean;
    /**
     * The list of MainDicomTags saved in DB for each resource level (new in Orthanc 1.11.0)
     */
    MainDicomTags?: object;
    /**
     * The configured MaximumStorageMode (new in Orthanc 1.11.3)
     */
    MaximumStorageMode?: string;
    /**
     * The configured MaximumStorageSize in MB (new in Orthanc 1.11.3)
     */
    MaximumStorageSize?: number;
    /**
     * The name of the Orthanc server, cf. the `Name` configuration option
     */
    Name?: string;
    /**
     * Whether instances are overwritten when re-ingested (new in Orthanc 1.11.0)
     */
    OverwriteInstances?: boolean;
    /**
     * Whether Orthanc was built with support for plugins
     */
    PluginsEnabled?: boolean;
    /**
     * Information about the installed storage area plugin (`null` if no such plugin is installed)
     */
    StorageAreaPlugin?: string;
    /**
     * Whether storage compression is enabled (new in Orthanc 1.11.0)
     */
    StorageCompression?: boolean;
    /**
     * The configured UserMetadata (new in Orthanc 1.12.0)
     */
    UserMetadata?: object;
    /**
     * Version of Orthanc
     */
    Version?: string;
}

