/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ToolsFindPostRequest { 
    /**
     * Enable case-sensitive search for PN value representations (defaults to configuration option `CaseSensitivePN`)
     */
    CaseSensitive?: boolean;
    /**
     * Also retrieve the content of the matching resources, not only their Orthanc identifiers
     */
    Expand?: boolean;
    /**
     * If set to `true`, report the DICOM tags in full format (tags indexed by their hexadecimal format, associated with their symbolic name and their value)
     */
    Full?: boolean;
    /**
     * List of strings specifying which labels to look for in the resources (new in Orthanc 1.12.0)
     */
    Labels?: Array<string>;
    /**
     * Constraint on the labels, can be `All`, `Any`, or `None` (defaults to `All`, new in Orthanc 1.12.0)
     */
    LabelsConstraint?: string;
    /**
     * Level of the query (`Patient`, `Study`, `Series` or `Instance`)
     */
    Level?: string;
    /**
     * Limit the number of reported resources
     */
    Limit?: number;
    /**
     * Associative array containing the filter on the values of the DICOM tags
     */
    Query?: object;
    /**
     * A list of DICOM tags to include in the response (applicable only if \"Expand\" is set to true).  The tags requested tags are returned in the \'RequestedTags\' field in the response.  Note that, if you are requesting tags that are not listed in the Main Dicom Tags stored in DB, building the response might be slow since Orthanc will need to access the DICOM files.  If not specified, Orthanc will return all Main Dicom Tags to keep backward compatibility with Orthanc prior to 1.11.0.
     */
    RequestedTags?: Array<string>;
    /**
     * If set to `true`, report the DICOM tags in hexadecimal format
     */
    Short?: boolean;
    /**
     * Show only the resources since the provided index (in conjunction with `Limit`)
     */
    Since?: number;
}

