/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ToolsDicomEchoPostRequest { 
    /**
     * AET of the remote DICOM modality
     */
    AET?: string;
    /**
     * Issue a dummy C-FIND command after the C-GET SCU, in order to check whether the remote modality knows about Orthanc. This field defaults to the value of the `DicomEchoChecksFind` configuration option. New in Orthanc 1.8.1.
     */
    CheckFind?: boolean;
    /**
     * Host address of the remote DICOM modality (typically, an IP address)
     */
    Host?: string;
    /**
     * Manufacturer of the remote DICOM modality (check configuration option `DicomModalities` for possible values
     */
    Manufacturer?: string;
    /**
     * TCP port of the remote DICOM modality
     */
    Port?: number;
    /**
     * Timeout for the C-ECHO command, in seconds
     */
    Timeout?: number;
    /**
     * Whether to use DICOM TLS in the SCU connection initiated by Orthanc (new in Orthanc 1.9.0)
     */
    UseDicomTls?: boolean;
}

