/**
 * Orthanc API
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ToolsBulkModifyPostRequest { 
    /**
     * If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.
     */
    Asynchronous?: boolean;
    /**
     * Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world
     */
    Force?: boolean;
    /**
     * Keep the original value of the specified tags, to be chosen among the `StudyInstanceUID`, `SeriesInstanceUID` and `SOPInstanceUID` tags. Avoid this feature as much as possible, as this breaks the DICOM model of the real world.
     */
    Keep?: Array<string>;
    /**
     * If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.
     */
    KeepSource?: boolean;
    /**
     * Level of the modification (`Patient`, `Study`, `Series` or `Instance`). If absent, the level defaults to `Instance`, but is set to `Patient` if `PatientID` is modified, to `Study` if `StudyInstanceUID` is modified, or to `Series` if `SeriesInstancesUID` is modified. (new in Orthanc 1.9.7)
     */
    Level?: string;
    /**
     * If `true`, ignore errors during the individual steps of the job.
     */
    Permissive?: boolean;
    /**
     * In asynchronous mode, the priority of the job. The lower the value, the higher the priority.
     */
    Priority?: number;
    /**
     * The private creator to be used for private tags in `Replace`
     */
    PrivateCreator?: string;
    /**
     * List of tags that must be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).
     */
    Remove?: Array<string>;
    /**
     * Remove the private tags from the DICOM instances (defaults to `false`)
     */
    RemovePrivateTags?: boolean;
    /**
     * Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).
     */
    Replace?: object;
    /**
     * List of the Orthanc identifiers of the patients/studies/series/instances of interest.
     */
    Resources?: Array<string>;
    /**
     * If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.
     */
    Synchronous?: boolean;
    /**
     * Transcode the DICOM instances to the provided DICOM transfer syntax: https://orthanc.uclouvain.be/book/faq/transcoding.html
     */
    Transcode?: string;
}

