export * from './instances.service';
import { InstancesService } from './instances.service';
export * from './jobs.service';
import { JobsService } from './jobs.service';
export * from './logs.service';
import { LogsService } from './logs.service';
export * from './networking.service';
import { NetworkingService } from './networking.service';
export * from './other.service';
import { OtherService } from './other.service';
export * from './patients.service';
import { PatientsService } from './patients.service';
export * from './series.service';
import { SeriesService } from './series.service';
export * from './studies.service';
import { StudiesService } from './studies.service';
export * from './system.service';
import { SystemService } from './system.service';
export * from './trackingChanges.service';
import { TrackingChangesService } from './trackingChanges.service';
export const APIS = [InstancesService, JobsService, LogsService, NetworkingService, OtherService, PatientsService, SeriesService, StudiesService, SystemService, TrackingChangesService];
